### ISSUE TITLE
Create a readme file

### ISSUE THREAD

**Issue by neutr0ncodes** [uday03meh/RockPaperScissors#1]
Create a readme file for the project

**Comment by uday03meh** [comment]
Go on, assigned it to you.

**Comment by chehe040** [comment]
Hi @uday03meh, Can you please assign this to me?

**Comment by uddinArsalan** [comment]
Hey @uday03meh, Can you assign this issue to me ?

**Comment by uday03meh** [comment]
Hi, you can work on some other issue or maybe create a new one while @chehe040 is working on this,

**Comment by uddinArsalan** [comment]
ok

**Comment by Ayushbajpai19** [comment]
If free, kindly assign this to me

**Comment by uday03meh** [comment]
@uddinArsalan, Can you work on this?

**Comment by uddinArsalan** [comment]
Sure @uday03meh

**Comment by uddinArsalan** [comment]
I have made a pull request @uday03meh

**Comment by Ayushbajpai19** [comment]
Can i still work on this issue?
