### ISSUE TITLE
Save current scores into local storage

### ISSUE THREAD

**Issue by Mano-08** [uday03meh/RockPaperScissors#11]
By doing so one wouldn't lose score data until 'Again' is clicked and every time they leave the website the scores remain intact. I would like to work on this feature, so would you please assign me to this task.

**Comment by uday03meh** [comment]
Is this same as #12? Can we close this issue if yes?

**Comment by Mano-08** [comment]
in #12 a new element has to be created & maintained but for this issue, we might need to store the 'scoreAfter' into localStorage every time it's updated.

Would it be good if highscores are never reset to zero but current scores can be reset to zero on clicking 'Again!' ?
So, the players can continue playing from where they left and if they want to restart they can just click "Again!" without resetting highScore to zero.

**Comment by uday03meh** [comment]
I think it will be better, Can you work on this one?

**Comment by Mano-08** [comment]
yeah, I can work on that.
