### ISSUE TITLE
redesign btn

### ISSUE THREAD

**Issue by shreypilot** [uday03meh/RockPaperScissors#16]
Hi @uday03meh
i would like to redesign btn 
please assign to me

**Comment by uday03meh** [comment]
You can work on it. Please do share the new design before making the PR.

**Comment by shreypilot** [comment]
yeah sure 
![Capture1](https://user-images.githubusercontent.com/104058567/195862209-262524b3-7efd-4b01-9726-39de853c3507.JPG)

**Comment by uday03meh** [comment]
You can make the PR for this change. Be sure not to change anything else.

**Comment by shreypilot** [comment]
Ok sure

**Comment by uday03meh** [comment]
Closed #23
