### ISSUE TITLE
Bug in functionality

### ISSUE THREAD

**Issue by priyanshi-git** [uday03meh/RockPaperScissors#2]
Even if both the computer and the player (me) have the same sign it say "You won" and increased the score. Shouldn't it show "draw" and not increase the score ? 
I am also seeing a similar issue with "draw" and "you lose". For reference I am adding snips below. 

![image](https://user-images.githubusercontent.com/82112540/195156432-01aaa8b0-a7a7-4c79-8364-c3ad07de7555.png)

![image](https://user-images.githubusercontent.com/82112540/195156694-6d89a76b-25bc-4284-b091-0b4d24b7eb4a.png)

**Comment by uday03meh** [comment]
Hi, Can you fix this? Shall I assign this to you?

**Comment by priyanshi-git** [comment]
I can give it a fair try 👉🏼👈🏼

**Comment by priyanshi-git** [comment]
Yes, I would like to work on this !
