### ISSUE TITLE
Reset Highscore button

### ISSUE THREAD

**Issue by uday03meh** [uday03meh/RockPaperScissors#20]
Hi, I'm thinking of having a "RESET" button which resets the highscore value to zero,

I need your feedback on this.

Either we can add it like this so that after hovering on "High Score", "RESET" button is displayed and can be clicked.
![image](https://user-images.githubusercontent.com/59679281/195849146-13f23c2d-806a-4e77-a1dc-e9e4746564c2.png)

Or we can add it below the highscore
![image](https://user-images.githubusercontent.com/59679281/195849267-a76f9bc7-cb2a-4865-abb2-cf101f94f6f2.png)

**Comment by uday03meh** [comment]
@Mano-08 What are your thoughts on this?

**Comment by manaslohani** [comment]
Can I have a go at this?

**Comment by uday03meh** [comment]
Yeah sure!

**Comment by Mano-08** [comment]
> @Mano-08 What are your thoughts on this?

Yeah, that's a good feature!
