### ISSUE TITLE
Add website's demo to README

### ISSUE THREAD

**Issue by uday03meh** [uday03meh/RockPaperScissors#27]
Hi, I want to add website's demo video, center aligned, and upto 10 seconds which uses all the buttons of the game in the beginning of the README.

**Comment by theobiabo** [comment]
i can work on this

**Comment by theobiabo** [comment]
can you assign it to me ?

**Comment by uday03meh** [comment]
Sure, Please share the changes here before making a PR.

**Comment by theobiabo** [comment]
This issue has been fixed in #29
