### ISSUE TITLE
Add keyboard interaction

### ISSUE THREAD

**Issue by l4ur4oliveira** [uday03meh/RockPaperScissors#31]
I would like to improve the project by adding some keyboard interaction.
I thought of using the inicials:

- [R] ock
- [P] aper
- [S] cissors

I'll submit a PR for your review.

**Comment by l4ur4oliveira** [comment]
Hi @uday03meh,
I noticed your rollback and this issue is still open.
Should I make any improvements to the code?

Let me know! 😊

**Comment by uday03meh** [comment]
Yeah, actually there were some issues with the deployment of the site after your PR so I had to revert that PR to check.

It's working fine now, Can you please make the same PR?

**Comment by l4ur4oliveira** [comment]
Sure!
