### ISSUE TITLE
Score not visible in mobile view.

### ISSUE THREAD

**Issue by sarthakastic** [uday03meh/RockPaperScissors#33]
UI is breaking in mobile view

<img width="1710" alt="Screenshot 2022-10-16 at 9 51 06 AM" src="https://user-images.githubusercontent.com/72138026/196017812-acc11c90-a154-4808-9aea-6a36d163d2e0.png">

**Comment by uday03meh** [comment]
Hi,
Thanks for pointing this issue, can you work on it?

**Comment by sarthakastic** [comment]
sure, can you pls assign it to me

**Comment by uday03meh** [comment]
You can work on it now

**Comment by uday03meh** [comment]
Hi, @sarthakastic any updates on this issue?

**Comment by priyanshi-git** [comment]
Hey ! this issue is working fine in my system 

![image](https://user-images.githubusercontent.com/82112540/196607795-a14eb1d2-481d-42d1-9dae-488f6996c5e2.png)
