### ISSUE TITLE
Reset score to zero after reloading

### ISSUE THREAD

**Issue by uday03meh** [uday03meh/RockPaperScissors#42]
Hi, I want the SCORE to reset to zero after reloading the page, and the HIGH SCORE to remain as it is. Currently both SCORE and HIGH SCORE retain their values after reloading.

Do comment if you want to work on this.

**Comment by ankitkumar0622** [comment]
hi can you assign me this task.

**Comment by uday03meh** [comment]
Sure!
I think only javascript file needs changes for this issue.

**Comment by Ved142** [comment]
Hey @uday03meh I would like to work on it. Please assign it to me.

**Comment by uday03meh** [comment]
Thanks for contributing!
I'm merging this PR but please let the assigned person do the PR or confirm if someone is working on that issue before contributing.
