### ISSUE TITLE
Add "View on GitHub" button

### ISSUE THREAD

**Issue by uday03meh** [uday03meh/RockPaperScissors#45]
Hi, I would like to add a button like this preferably at the bottom of the page, centered horizontally which links to the GitHub repository of this project.

![image](https://user-images.githubusercontent.com/59679281/197393963-b31f8504-1cba-4a68-97b9-6f167fe66341.png)

You can choose color, background color, hover and active state as you wish, but do share a screenshot here before making a Pull Request.

**Comment by zainbinfurqan** [comment]
@uday03meh  can i work on it please?

**Comment by uday03meh** [comment]
Yes, Go on!

**Comment by Utkarsh404-crypto** [comment]
Hey! @uday03meh, I would like to add the button on the page. Can you assign me this task?

**Comment by Utkarsh404-crypto** [comment]
Hey! @uday03meh , it will look something like this on hover with some transition.
![Screenshot (90) copy](https://user-images.githubusercontent.com/68241943/197403875-d92371c1-af47-4dae-a28b-ef7954ca1054.png)

**Comment by vinay4563** [comment]
@uday03meh I have done like this to match the theme of game. On hover the background color will change to grey

Suggestions are welcomed !

![image](https://user-images.githubusercontent.com/89059291/197453102-2956a35e-6114-4c5f-aa94-72c571697469.png)

**Comment by uday03meh** [comment]
Hi @Utkarsh404-crypto and @vinay4563 , 
Thanks for contributing, please wait before making a Pull Request as this issue is assigned to @zainbinfurqan .

**Comment by Utkarsh404-crypto** [comment]
@uday03meh sure!! , but please let me know.

**Comment by zainbinfurqan** [comment]
@uday03meh  it will be hover icon
![12](https://user-images.githubusercontent.com/30855000/197608830-d6de84a1-e3f0-406f-852b-7dd9cfb24f30.PNG)

**Comment by uday03meh** [comment]
@zainbinfurqan You can make the PR, it looks good to me.

**Comment by zainbinfurqan** [comment]
@uday03meh  you can review it. [MR](url[)](https://github.com/uday03meh/RockPaperScissors/pull/48)
