### ISSUE TITLE
Adding attractive Header

### ISSUE THREAD

**Issue by shrutigajbhiye22** [uday03meh/RockPaperScissors#49]
I would like to add attractive header to the page.

**Comment by shrutigajbhiye22** [comment]
Hey @uday03meh ! 
I would like to work on this issue, could you please assign me this issue under the tag of hactoberfest?

**Comment by uday03meh** [comment]
Hi @shrutigajbhiye22 ,
Can you please share a screenshot of what you are planning to add before making a Pull Request?

**Comment by shrutigajbhiye22** [comment]
I'm really sorry, but I realised that adding header won't look good. Really sorry for creating inappropriate issue :(
and to compensate that I've made some changes, which you might like.

https://user-images.githubusercontent.com/96727722/197659319-531c9d61-43a4-4eb6-93e4-cc04f212094b.mp4

I have tried to make it look more neat and consistent and more aligned. 
Like, by adding space in Rock paper Scissor, increasing font size, increased space between buttons, changed colour of hovering effect on buttons, also changed colour of button to more go-to green colour.

Could you assign me this, under hactoberfest tag please?

**Comment by uday03meh** [comment]
Hey, it's alright.
These changes look good in desktop mode, don't change the background colors of buttons or hovering effect but please make sure they are responsive as well before making a Pull Request.

**Comment by shrutigajbhiye22** [comment]
Yeah it's responsive :)
In fact it was a bug that the view was inconsistent in desktop mode.

**Comment by uday03meh** [comment]
Okay,  you can create a Pull Request.

**Comment by shrutigajbhiye22** [comment]
https://user-images.githubusercontent.com/96727722/197754923-5922006f-c773-4c46-a70c-b45a53ab46ef.mp4

How's this then?

**Comment by shrutigajbhiye22** [comment]
Did you not merge it in your repo?

**Comment by shrutigajbhiye22** [comment]
Sorry, hactoberfest showed not-accepted by maintainer till now.
but now it's accepted.
Sorry for the trouble and thank you!

**Comment by uday03meh** [comment]
No worries :)
Keep Contributing!
