### ISSUE TITLE
Change title and favicon

### ISSUE THREAD

**Issue by uday03meh** [uday03meh/RockPaperScissors#6]
This is the how current title and favicon looks like.

![image](https://user-images.githubusercontent.com/59679281/195190028-90aed86a-4f21-422c-af81-f2aa4f1722ed.png)

Add a suitable title and a favicon

**Comment by chehe040** [comment]
Hi, I would like to work on this. Can you please assign this to me?

**Comment by Ayushbajpai19** [comment]
I would love to work on this issue, maybe we can distribute our work, one can change the title and another one can change the favicon, please can you add me, I ould like to contribute.

**Comment by shreypilot** [comment]
Hi @uday03meh
can you please  assign to me 
i would like to add best favico and title

**Comment by uday03meh** [comment]
@chehe040 Are you still working on this?

**Comment by uday03meh** [comment]
Closed under #22
