### ISSUE TITLE
Change Text color according to win , loss or draw

### ISSUE THREAD

**Issue by gkumar-pandey** [uday03meh/RockPaperScissors#8]
Hii @uday03meh 
i would like to add a feature when user win the text color renders in green, loss then Red and draw then yellow 
please assign to me

**Comment by uday03meh** [comment]
Hi, Are you planning to change color of "Your Score" or "You won" part?

![image](https://user-images.githubusercontent.com/59679281/195328190-cab7a9e4-800b-408d-9a1a-4ce63eb1731b.png)

**Comment by gkumar-pandey** [comment]
You won text

**Comment by uday03meh** [comment]
Okay, you can work on it.
