### ISSUE TITLE
Added a new page

### ISSUE THREAD

**Issue by ananyajain10** [uday03meh/RockPaperScissors#9]
Hey, I would like to add a start page in this game. Have a look and If you like it assign it to me 💫

<img width="960" alt="image" src="https://user-images.githubusercontent.com/78138175/195358118-d09dd2f5-0294-4ea4-8f89-be526b9b7aba.png">

**Comment by uday03meh** [comment]
Hi, I'm not sure whether this will be a good idea or not, but you can still give it a try and make a PR. Also try to use [Contrast Checker](https://coolors.co/contrast-checker/112a46-acc8e5) for the button design.

**Comment by ananyajain10** [comment]
Sorry by mistake I've clicked unassign , you can reassign it.

**Comment by ananyajain10** [comment]
Hey please send me invite link and access permission to contribute. I'm unable to puch changes 🤕

**Comment by uday03meh** [comment]
You have to fork the project first then you'll be able to push your changes.

After forking it should be visible in "Repositories" section of your profile.

![image](https://user-images.githubusercontent.com/59679281/195449946-163c95e7-11ea-493c-9778-966540577271.png)
